server:
  port: 8082
spring:
  datasource:
    name: DB_USER
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true